dev:
  hostname: localhost-dev
  port:     5432
  database: dev
  username: root
  password: 123456
  sslmode: disable

test:
  hostname: localhost-test
  port:     5432
  database: test
  username: root
  password: a1937258
  sslmode: disable

prod:
  hostname: localhost-prod
  port:     5432
  database: prod
  username: root
  password: a1937258
  sslmode: enable
